# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('message', models.TextField(verbose_name='mensagem')),
            ],
            options={
                'ordering': ('-created_at',),
                'verbose_name': 'email',
                'verbose_name_plural': 'emails',
            },
        ),
    ]
